---
title: "Project Work"
author: "Eleanor and Wriley"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(sf)
library(leaflet)
library(glue)
```

```{r clean-2022}
nest_count_2022 <- read_excel("data/nest_count/nest_count_2022.xlsx", na = "NA")

nest_count_2022 <- nest_count_2022 %>%
  mutate(year = "2022") %>%
  mutate(species = str_extract(comment, "\\d*GBBG|\\d*COEI")) %>%
  mutate(species = str_replace(species, "COEI", "coei")) %>%
  mutate(species = str_replace(species, "GBBG", "gbbg")) %>%
  replace_na(list(species = "herg")) %>%
  select(Flag, clutch, location, year, species) %>%
  rename(flag = Flag)
```

```{r clean-2021}
nest_count_2021 <- read_excel("data/nest_count/nest_count_2021.xlsx", na = "NA")

nest_count_2021 <- nest_count_2021 %>%
  mutate(year = "2021") %>%
    mutate(detect.gbbg = str_detect(comment, "GBBG")) %>% 
    mutate(detect.gbbg.2 = str_detect(`...7`, "GBBG")) %>%
    mutate(detect.coei = str_detect(comment, "eider")) %>%
    mutate(detect.coei.2 = str_detect(`...7`, "COEI")) %>%
    mutate(species = case_when(
      detect.gbbg == "TRUE" | detect.gbbg.2 == "TRUE" ~ "gbbg",
      detect.coei == "TRUE" | detect.coei.2 == "TRUE" ~ "coei")) %>%
  replace_na(list(species = "herg")) %>%
  select(flag, clutch, location, year, species)
```

```{r clean-2020}
nest_count_2020 <- read_excel("data/nest_count/nest_count_2020.xlsx", na = "NA")

unique(nest_count_2020$comment)
head(nest_count_2020)

nest_count_2020 <- nest_count_2020 %>%
  mutate(year = "2020") %>%
  mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))) %>%
  select(flag, clutch, location, year, species)
```

```{r clean-2019}
nest_count_2019 <- read_excel("data/nest_count/nest_count_2019.xlsx", na = "NA")

unique(nest_count_2019$comment)

nest_count_2019 <- nest_count_2019 %>%
  mutate(year = "2019") %>%
  mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))) %>%
  select(nest, clutch, location, year, species) %>%
  rename(flag = nest)
```
```{r clean-2018}
nest_count_2018 <- read_excel("data/nest_count/nest_count_2018.xlsx", na = "NA")

unique(nest_count_2018$comment)

nest_count_2018 <- nest_count_2018 %>%
  mutate(year = "2018") %>%
  mutate(species = ifelse(grepl("Black-back", comments), "gbbg",
                          ifelse(grepl("Black back", comments), "gbbg",
                          ifelse(grepl("black-back", comments), "gbbg",
                          ifelse(grepl("Black-Back", comments), "gbbg",
                          ifelse(grepl("GBBG", comments), "gbbg",
                          ifelse(grepl("gbbg", comments), "gbbg",
                          ifelse(grepl("Eider", comments), "coei",
                          ifelse(grepl("eider", comments), "coei", 
                          ifelse(grepl("Edier", comments), "coei",
                          ifelse(grepl("COEI", comments), "coei",
                          ifelse(grepl("coei", comments), "coei",
                          "herg")))))))))))) %>%
  select(nest, clutch, location, year, species) %>%
  rename(flag = nest)

```
```{r clean-2017}
nest_count_2017 <- read_excel("data/nest_count/nest_count_2017.xlsx", na = "NA")

unique(nest_count_2017$comment)

nest_count_2017 <- nest_count_2017 %>%
  mutate(year = "2017") %>%
  rename(comment = "Desc.",
         location = "loc.",
         clutch = Clutch,
         flag = Nest) %>%
  mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))) %>%
  select(flag, clutch, location, year, species)
```
```{r clean-2016}
nest_count_2016 <- read_excel("data/nest_count/nest_count_2016.xlsx", na = "NA")

nest_count_2016 <- nest_count_2016 %>%
  mutate(year = "2016") %>%
   rename(comment = "Info",
         clutch = Clutch,
         flag = Flag) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))) %>%
  select(flag, clutch, year, species) 
```

```{r clean-2015}
nest_count_2015 <- read_excel("data/nest_count/nest_count_2015.xlsx", na = "NA")

nest_count_2016 <- nest_count_2016 %>%
  mutate(year = "2016") %>%
   rename(comment = "Info",
         clutch = Clutch,
         flag = Flag) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))) %>%
  select(flag, clutch, year, species) 


```



```{r}
write.csv(nest_count_2021, "data/nest_count_clean_2021.csv")

write.csv(nest_count_2022, "data/nest_count_clean_2022.csv")

```

