---
title: "tower count data cleaning"
author: "Eleanor and Wriley"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(viridis)
library(hrbrthemes)
library(sf)
library(leaflet)
library(lubridate)
```



```{r column rename function}
#lists of possible columns names for our usual birds, add as new ones arise
hergs <- c("gulls","hegu","HERG","Gull","# gulls", "HeGu","HerGull")
gbbgs <- c("bbgu","GBBG","BBGull")
blgus <- c("# squees", "squees","BLGU","Guillem", "BGUY", "squee")
coei_jus <-c("chix","eider chicks", "COEI ducklings", "Eider Chicks","COEI chix","COEI  chix")
coei_ads <- c("COEI","Eiders", "# eiders", "eider","eiders", "coei")
others <- c("Other","notes","comments","others", "Others", "comment","Comments")
dates <- c("Date")
puffins <- c("ATPU","AtPu")

cleancolumns <- function(inputdataframe) {
  for (i in 1:length(colnames(inputdataframe))){
      if (colnames(inputdataframe)[i] %in% hergs) {
        colnames(inputdataframe)[i] <- "herg"
        print("hergs")
    } else if(colnames(inputdataframe)[i] %in% gbbgs) {
        colnames(inputdataframe)[i] <- "gbbg"
        print("gbbgs")
    } else if (colnames(inputdataframe)[i] %in% blgus) {
      colnames(inputdataframe)[i] <- "blgu"
      print("blgus")
    } else if (colnames(inputdataframe)[i] %in% coei_jus) {
      colnames(inputdataframe)[i] <- "coei_ju"
      print("coei_jus")
    } else if (colnames(inputdataframe)[i] %in% coei_ads) {
      colnames(inputdataframe)[i] <- "coei_ad"
      print("coei_ads")
    } else if (colnames(inputdataframe)[i] %in% others) {
      colnames(inputdataframe)[i] <- "other"
      print("other")
    } else if (colnames(inputdataframe)[i] %in% dates) {
      colnames(inputdataframe)[i] <- "date"
      print("dates")
    } else if (colnames(inputdataframe)[i] %in% puffins) {
      colnames(inputdataframe)[i] <- "puffin"
      print("puffins")
    }
  }
  return(inputdataframe)
}

```

```{r comment split function}
splitcomments <- function(inputdataframe) {
  r <- inputdataframe %>% 
    #puffins
  mutate(puffin = str_extract(other, "\\d*puff|\\d*.puff|\\d*atpu|\\d*.atpu|\\d*puffis|\\d*puffins|\\d*.puffins|\\d*.ATPU|\\d*.ALPU|\\d*.puffin|\\d*..ATPU")) %>% 
  mutate(puffin = as.double(str_extract(puffin, "\\d*"))) %>%
    #cormorants
  mutate(dcco = str_extract(other, "\\d*corm|\\d*dcc|\\d*dcco|\\d*ddco|\\d*.DCCO|\\d*.DCC0|\\d*.commorants|\\d*.corm|\\d*.cormorants|d*..corm|\\d*.dcco")) %>% 
  mutate(dcco = as.double(str_extract(dcco, "\\d*"))) %>% 
    #terns
  mutate(ternsp = str_extract(other, "\\d*cote|\\d*.terns|\\d*.COTE|\\d*.ARTE|\\d*.Terns|\\d*.Tern|\\d*.arte|\\d*.common tern|\\d*.common term")) %>% 
  mutate(ternsp = as.double(str_extract(ternsp, "\\d*"))) %>%
    #razorbills
  mutate(razo = str_extract(other, "\\d*razo|\\d*razor|\\d*.RAZO|\\d*.razorbills|\\d*.bills|\\d*.bill|\\d*.RAZ0")) %>% 
  mutate(razo = as.double(str_extract(razo, "\\d*"))) %>% 
    #laughing gulls
  mutate(lagu = str_extract(other, "\\d*lagu|\\d*.laughing|\\d*.LAGU|\\d*lagus")) %>% 
  mutate(lagu = as.double(str_extract(lagu, "\\d*"))) %>% 
    #common murre
  mutate(comu = str_extract(other, "\\d*murre|\\d*.COMU|\\d*.common murre|\\d*.murre")) %>% 
  mutate(comu = as.double(str_extract(comu, "\\d*"))) %>% 
    #bald eagle
  mutate(baea = str_extract(other, "\\d*.imm|\\d*.BAEA|\\d*.eagle")) %>% 
  mutate(baea = as.double(str_extract(baea, "\\d*"))) %>% 
    #gannet
  mutate(noga = str_extract(other, "\\d*.gannets||\\d*.NOGA|\\d*.gannet")) %>% 
  mutate(noga = as.double(str_extract(noga, "\\d*"))) %>% 
    #corvids
  mutate(corvid = str_extract(other, "\\d*.crow|\\d*.Corvid|\\d*.AMCR|\\d*.Corvids|\\d*.crows|\\d*crow")) %>% 
  mutate(corvid = as.double(str_extract(corvid, "\\d*"))) %>%
    #sandpipers
  mutate(peepsp = str_extract(other, "\\d*.SPSA|\\d*.WHIM|\\d*..SPSA|\\d*.spotted sandpiper|\\d*.least sandpiper|\\d*.pipers|\\d*.common sandpipers|\\d*.piper")) %>% 
  mutate(peepsp = as.double(str_extract(peepsp, "\\d*"))) %>% 
    #seals
  mutate(seals = str_extract(other, "\\d*.Seal|\\d*.Seals|\\d*.Harbor|\\d*.Gray|\\d*.seals|\\d*.grey|\\d*.seal|\\d*.harbor|\\d*.gray|\\*.Grey|\\d*.Grey Seal|\\d*.Grey Seals|\\d*.harbor seal|\\d*.gray seal")) %>% 
  mutate(seals = as.double(str_extract(seals, "\\d*"))) %>% 
    #Loons
  mutate(colo = str_extract(other, "\\d*.COLO|\\d*.loon|\\d*.loons")) %>% 
  mutate(colo = as.double(str_extract(colo, "\\d*"))) %>% 
    #geese
  mutate(cago = str_extract(other, "\\d*.CAGO|\\d*.goose|\\d*.canada goose")) %>% 
  mutate(cago = as.double(str_extract(cago, "\\d*"))) %>% 
    #porpoise
  mutate(porpoise = str_extract(other, "\\d*.Harbor|\\d*.porpoise|\\d*.Porpoises|\\d*.porpoises")) %>% 
  mutate(porpoise = as.double(str_extract(porpoise, "\\d*"))) %>% 
    #raptors
  mutate(raptor = str_extract(other, "\\d*.tv")) %>% 
  mutate(raptor = as.double(str_extract(raptor, "\\d*"))) %>% 
    #shearwater
  mutate(shearwater = str_extract(other, "\\d*.shearwater")) %>% 
  mutate(shearwater = as.double(str_extract(shearwater, "\\d*"))) %>% 
    #heron
  mutate(gbhe = str_extract(other, "\\d*.heron|\\d*.GBHE")) %>% 
  mutate(gbhe = as.double(str_extract(gbhe, "\\d*"))) %>% 
    #scoter
  mutate(scoter = str_extract(other, "\\d*.scoter|\\d*.Scoter|\\d*.BLSC")) %>% 
  mutate(scoter = as.double(str_extract(scoter, "\\d*")))
  return(r)
}


```


```{r select columns and pivot}
selectcolumns <- function(inputdataframe) {
  r <- inputdataframe %>% 
    mutate(notes = other) %>% 
    select("date","herg","gbbg","coei_ad","coei_ju","blgu","other","puffin","dcco","ternsp","razo","lagu","comu","baea","noga","corvid","peepsp","seals","colo","cago","porpoise","raptor","gbhe","scoter","shearwater","notes") %>% 
    mutate(herg = as.numeric(herg), gbbg = as.numeric(gbbg), coei_ad = as.double(coei_ad), coei_ju = as.double(coei_ju), blgu = as.double(blgu)) %>% 
    pivot_longer(cols = c("herg","gbbg","coei_ad","coei_ju","blgu","puffin","dcco","ternsp","razo","lagu","comu","baea","noga","corvid","peepsp","seals","colo","cago","porpoise","raptor", "gbhe","scoter","shearwater"),
                 names_to = "species",
                 values_to = "count") %>% 
    select(date, species, count, notes)
  return(r)
}
```


```{r 2000}
tower_count_2000 <- read_excel("data/tower_count/tower_count_2000.XLS")
tower_count_2000 <- tower_count_2000[2:48,]
tower_count_2000 <- tower_count_2000 %>%
  mutate(coei_ju = as.double(str_extract(`# eiders`, "(?<=\\().*(?=\\))"))) %>% 
  mutate(`# eiders` = as.double(str_extract(`# eiders`, "\\d*"))) %>% 
  mutate(gbbg = NA)


tower_count_2000 <- cleancolumns(tower_count_2000)
tower_count_2000 <- splitcomments(tower_count_2000)
tower_2000_clean <- selectcolumns(tower_count_2000)
```




```{r 2001}
tower_count_2001 <- read_excel("data/tower_count/tower_count_2001.xlsx", skip = 2)
tower_count_2001 <- tower_count_2001 %>% 
  mutate(GBBG = case_when(GBBG == "-" ~ "NA",
         TRUE ~ as.character(GBBG)))

tower_count_2001 <- cleancolumns(tower_count_2001)
tower_count_2001 <- splitcomments(tower_count_2001)
tower_2001_clean <- selectcolumns(tower_count_2001)
```

```{r 2002}
tower_count_2002 <- read_excel("data/tower_count/tower_count_2002.xlsx", skip = 2)

tower_2002_clean <- tower_count_2002 %>% 
  cleancolumns() %>% 
  splitcomments() %>% 
  selectcolumns()
  
```

```{r 2003}
tower_count_2003 <- read_excel("data/tower_count/tower_count_2003.xls")

tower_count_2003 <- tower_count_2003 %>% 
  mutate(coei_ad = str_extract(Eider, "^(.+)/|^(.+)")) %>% 
  mutate(coei_ad = as.double(str_extract(coei_ad,"\\d*"))) %>%
  mutate(coei_ju = str_extract(Eider, "\\/.*")) %>% 
  mutate(coei_ju = as.double(str_extract(coei_ju, "\\d*$")))

tower_count_2003 <- cleancolumns(tower_count_2003)
tower_count_2003 <- splitcomments(tower_count_2003)
tower_2003_clean <- selectcolumns(tower_count_2003)
```

```{r 2005}
tower_count_2005 <- read_excel("data/tower_count/tower_count_2005.xls")

tower_count_2005 <- tower_count_2005 %>% 
  mutate(other = NA)

tower_count_2005 <- cleancolumns(tower_count_2005)
tower_count_2005 <- splitcomments(tower_count_2005)
tower_2005_clean <- selectcolumns(tower_count_2005)
```

```{r 2006}
tower_count_2006 <- read_excel("data/tower_count/tower_count_2006.xls")

tower_count_2006 <- cleancolumns(tower_count_2006)
tower_count_2006 <- splitcomments(tower_count_2006)
tower_count_2006 <- tower_count_2006 %>% 
  mutate(coei_ju = as.double(str_extract(other, "\\d*eiderchix")))
tower_2006_clean <- selectcolumns(tower_count_2006)
```

```{r 2007}
tower_count_2007 <- read_excel("data/tower_count/tower_count_2007.xls")

tower_count_2007 <- cleancolumns(tower_count_2007)
tower_count_2007 <- splitcomments(tower_count_2007)
tower_2007_clean <- selectcolumns(tower_count_2007)
```

```{r 2008}
tower_count_2008 <- read_excel("data/tower_count/tower_count_2008.xlsx", skip = 2)

tower_count_2008 <- cleancolumns(tower_count_2008)
tower_count_2008 <- splitcomments(tower_count_2008)
tower_2008_clean <- selectcolumns(tower_count_2008)

```

```{r 2009}
tower_count_2009 <- read_excel("data/tower_count/tower_count_2009.xlsx", skip = 2)

tower_count_2009 <- cleancolumns(tower_count_2009)
tower_count_2009 <- splitcomments(tower_count_2009)
tower_2009_clean <- selectcolumns(tower_count_2009)
```

```{r 2010}
tower_count_2010 <- read_excel("data/tower_count/tower_count_2010.xlsx",skip = 2)

tower_2010_clean <- tower_count_2010 %>% 
  cleancolumns() %>% 
  splitcomments() %>% 
  selectcolumns()

```


```{r 2011}
tower_count_2011 <- read_excel("data/tower_count/tower_count_2011.xls", skip = 2)
tower_count_2011 <- tower_count_2011[1:47,]
tower_count_2011 <- tower_count_2011 %>% 
  mutate(year = "2011") %>% 
  mutate(day = str_sub(Date, start = 1, end = 2)) %>% 
  mutate(monthch = str_sub(Date, start = 3,)) %>% 
  mutate(month = case_when(monthch %in% "June" ~ "6",
                           monthch %in% " June" ~ "6",
                           monthch %in% " July" ~ "7",
                           monthch %in% " August" ~ "8",
                           monthch %in% "July" ~ "7",
                           monthch %in% "August" ~ "8",
                           TRUE ~ ""
                           )) 

tower_count_2011 <- cleancolumns(tower_count_2011)
tower_count_2011 <- splitcomments(tower_count_2011)
tower_2011_clean <- selectcolumns(tower_count_2011)

```


```{r 2012}
#this isn't working, may have to be done by hand. Unfortunately the splitcomments function overwrites the contents of the pre-existing columns. The best thing to do may be to somehow pivot those columns so they appear as comments in a different column, then paste them together. 

#this is an extremely inelegant solution to this problem but it does seem to work. It is probably possible to write a loop to do it. 
tower_count_2012 <- read_excel("data/tower_count/tower_count_2012.xls", skip = 2) %>% 
  mutate(ATPU = paste(ATPU, "atpu"),RAZO = paste(RAZO, "razo"), DCCO = paste(DCCO, "dcco"),AMCR = paste(AMCR, "crow"),CORA = paste(CORA, "corvid"), COLO = paste(COLO, "COLO"), NOGA = paste(NOGA, "gannet"),BAEA = paste(BAEA, "eagle"),LAGU = paste(LAGU,"lagu"),COTE = paste(COTE, "tern"), SPSA = paste(SPSA, "piper")) %>% 
  mutate(Comments = paste(Comments, ATPU, RAZO, DCCO, AMCR, CORA, COLO, NOGA, BAEA, LAGU, COTE, sep = "," ))
#This is very unlikely to be adding the corvids together properly, but that should only be a problem if there are crows and ravens observed on the same day. Not sure if worth fixing, though would be interesting to try. 

tower_count_2012 <- cleancolumns(tower_count_2012)
tower_count_2012 <- splitcomments(tower_count_2012)
tower_2012_clean <- selectcolumns(tower_count_2012)
```

```{r 2013}

#same problem as above
tower_count_2013 <- read_excel("data/tower_count/tower_count_2013.xls")%>% 
  mutate(ATPU = paste(ATPU, "atpu"),RAZO = paste(RAZO, "razo"), DCCO = paste(DCCO, "dcco"), COLO = paste(COLO, "COLO"), NOGA = paste(NOGA, "gannet"),BAEA = paste(BAEA, "eagle"),LAGU = paste(LAGU,"lagu"),tern = paste(tern, "tern"), scoter = paste(scoter, "scoter"), seal = paste(seal, "seal")) %>% 
  mutate(other = paste(other, ATPU, RAZO, DCCO, COLO, NOGA, BAEA, LAGU, tern, scoter, seal, sep = "," ))

tower_count_2013 <- cleancolumns(tower_count_2013)
#worth checking if puffins are carrying over correctly
tower_count_2013 <- splitcomments(tower_count_2013)
tower_2013_clean <- selectcolumns(tower_count_2013)
```

```{r}
tower_count_2014 <- read_excel("data/tower_count/tower_count_2014.xlsx")
#thank god a normal one

tower_count_2014 <- cleancolumns(tower_count_2014)
tower_count_2014 <- splitcomments(tower_count_2014)
tower_2014_clean <- selectcolumns(tower_count_2014)
```

```{r}
tower_count_2015 <- read_excel("data/tower_count/tower_count_2015.xlsx")

tower_count_2015 <- cleancolumns(tower_count_2015)
tower_count_2015 <- splitcomments(tower_count_2015)
tower_2015_clean <- selectcolumns(tower_count_2015)
```

