---
title: "Exploring Great Duck Island Through Data"
author: "Eleanor and Wriley"
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
```

## 1. Introduction

In this project, we will use existing data about the seabirds breeding on Great Duck Island to explore their ecologies and distributions. Much of this data was collected for long-term monitoring or for student projects that have been completed. We hope that by re-visiting some of this data from a higher-level and data-focused perspective, we will be able to tease out some new information about the island that has yet to be discovered. We are particularly interested in exploring the spatial distribution of the seabird colonies on GDI and how they have changed over time. The first part of our project will focus on visualizing how the gull colony on the south end of the island has changed since 1999, allowing us to develop spatial visualization skills in R. Next, we hope to bring in several years' worth of chick-check data containing chick growth metrics. This will doubtless require a great deal of data tidying, but should yield some interesting visualizations and insights. Doing this will also allow us to consider a best practice for the future collection of this type of data. Later, we may want to tidy and analyze other data including band return data, petrel habitat surveys, gull GPS-tracker data, and more. An ideal outcome of this project would be a tidier and more accessible data storage system for Great Duck Island that would help further researchers collect and organize data in a more productive way. 

## 2. Data



## 3. Data analysis plan



