---
title: "Exploring Long-Term Datasets from Great Duck Island"
subtitle: ""
author: "Wriley and Eleanor"
institute: "College of the Atlantic"
date: "`r Sys.Date()`"

---

##This will be used to create figures used for our presentation. Alt text should be included here as well as in the Google Slides. 

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(viridis)
library(hrbrthemes)
library(RColorBrewer)
library(wesanderson)
library(sf)
library(leaflet)
library(gganimate)
library(ggimage)
library(gifski)
library(transformr)
library(forcats)
library(visdat)
```

##Changes in the Gull Colony Distribution Over Time

```{r}
all.nest.count <- read.csv("data/all.nest.count.csv")
```

```{r fig.height=2.5, fig.width=5, fig.alt = "A bar graph showing the total number of nests on Great Duck Island from 1999 - 2022. The y axis shows the total number of nests, while the x axis represents year. There is a major outlier in 2010, but this was due to faulty data collection and is unlikely to actually be representative of overall changes. We can see that the overall population   increased from 1999 to 2015 from about 600 nests in 1999 to 1200 in 2015 (though note that there were about 900 in 2000). The population has been slowly decreasing since 2015"}

all.nest.count %>%
  group_by(year, species) %>%
  count(species) %>%
  filter(species == "herg") %>%
  ggplot() +
  geom_col(aes(x = year, y = n), fill = "#9EC2FF") +
  theme_bw() +
    labs(title = "Total Number of Herring Gulls Nesting on Great Duck",
         subtitle = "From 1999 to 2022",
         y = "Number of Nests", 
         x = "Year")

ggsave("total_herg_nests.jpeg", device = "jpeg", dpi = 2500)
```

```{r fig.height=2, fig.width=5, fig.alt="A bar graph showing changes in the number of great black backed gulls nesting on Great Duck. The y axis shows the total number of nests, while the x axis shows the year. Black backed gulls are difficult to accurately count, so we are unsure of exactly how accurate this data is, but it seems to show that gbbgs peaked in the early 2010s, and have been nesting at lower levels since."}
all.nest.count %>%
  group_by(year, species) %>%
  count(species) %>%
  filter(species == "gbbg") %>%
  ggplot() +
  geom_col(aes(x = year, y = n), fill = "#9EC2FF") +
  theme_bw() +
    labs(title = "Changes in Nesting Great Black-backed Gulls from 1999 to 2022",
         y = "Number of Nests", 
         x = "Year")

ggsave("total_gbbg_nests.jpeg", device = "jpeg", dpi = 700)
```
```{r fig.height=2, fig.width=5, fig.alt="A bar graph showing changes in the number of common eiders nesting on Great Duck. The y axis shows the total number of nests, while the x axis shows the year. Common eiders are very cryptic nesters and are difficult to accurately count, so we are unsure of exactly how accurate this data is, but it seems to show that the number of eiders have been steadily rising"}
all.nest.count %>%
  group_by(year, species) %>%
  count(species) %>%
  filter(species == "coei") %>%
  ggplot() +
  geom_col(aes(x = year, y = n), fill = "#9EC2FF") +
  theme_bw() +
    labs(title = "Changes in Nesting Common Eiders from 1999 to 2022",
         y = "Number of Nests", 
         x = "Year")

ggsave("total_coei_nests.jpeg", device = "jpeg", dpi = 700)
```
```{r cleaning-population-distribution}
population_distribution_gulls <- read_xlsx(str_c("data/gull_pop_distribution_2022.xlsx")) 
population_distribution_gulls$West[3]=193 

population_distribution_gulls_cleaned <- population_distribution_gulls %>%
  rename(little_point = `Little Point (near Boathouse)`) %>%
  mutate(West = as.numeric(`West`)) %>%
  mutate(south_end = East + West + Extension) %>%
  mutate(north_end = Point + Cabin + Hell) %>%
  select(YEAR, south_end, north_end, Borofsky, little_point) %>%
  pivot_longer(cols = south_end:little_point,
               names_to = "location",
               values_to = "total")
```


```{r dodged-barplot-whole-island, echo = FALSE,  fig.height=3, fig.width=6, fig.alt = "a dodged barplot showing changes in how gull nests are distributed among GDI's sub-colonies over time. The total number of nests is mapped on the y axis, and year is on the x axis. Each year has four columns, one for each sub-colony. Over time, the Borofsky colony and the Little Point colony have gone extinct. The north end colony has declined from a peak of around 440 nests in 2000 to a low of around 240 nests in 2022. The south end colony has increased from a low of 250 nests in 1999 to consistently above 750 nests since 2014." }

population_distribution_gulls_cleaned %>%
  filter(location != "little_point") %>%
  mutate(location = str_replace(location, "Borofsky", "Borofsky Colony"), 
         location = str_replace(location,  "north_end", "North End Colony"),
         location = str_replace(location,  "south_end", "South End Colony")
         ) %>%
  ggplot(aes(y = total, x = YEAR, fill = location)) +
  geom_col(position = "dodge", width = 1, color = "black") +
   # scale_fill_manual(values = c("#00264D", "#4259C3", "#9EC2FF")) +
  scale_fill_manual(values = c("#00264D", "#4259C3", "#9EC2FF")) +
  theme_bw() +
  labs(y = "Total Number of Nesting Gulls", 
       x = "Year",
       fill = "Location")

ggsave("proportion_subcolonies.jpeg", device = "jpeg", dpi = 500)

```


```{r  echo = FALSE, dodged-barplot-south-end}
population_distribution_gulls %>%
  rename(little_point = `Little Point (near Boathouse)`) %>%
  mutate(West = as.numeric(`West`)) %>%
  select(YEAR, East, West, Extension) %>%
  pivot_longer( cols = East:Extension,
               names_to = "location",
               values_to = "total") %>%
  ggplot(aes(y = total, x = YEAR, fill = location)) +
  geom_col(position = "dodge", width = 1, color = "white") +
  scale_fill_manual(values = c("#9EC2FF", "#4259C3","#00264D")) +
  labs(title = "Distribution of Nests within the South End Colony") +
  theme_bw()
```

```{r echo = FALSE, filled-barplot-whole-island}
population_distribution_gulls %>%
  rename(little_point = `Little Point (near Boathouse)`) %>%
  mutate(West = as.numeric(`West`)) %>%
  mutate(south_end = East + West + Extension) %>%
  mutate(north_end = Point + Cabin + Hell) %>%
  filter(!is.na(south_end)) %>% 
  select(YEAR, south_end, north_end, Borofsky, little_point) %>%
  pivot_longer( cols = south_end:little_point,
               names_to = "location",
               values_to = "total") %>%
  ggplot(aes(y = total, x = YEAR, fill = location)) +
  geom_col(position = "fill") +
   scale_fill_viridis(discrete = T) +
  theme_bw()
```

```{r echo = FALSE, stacked-barplot-whole-island}

population_distribution_gulls %>%
  rename(little_point = `Little Point (near Boathouse)`) %>%
  mutate(West = as.numeric(`West`)) %>%
  mutate(south_end = East + West + Extension) %>%
  mutate(north_end = Point + Cabin + Hell) %>%
  filter(!is.na(south_end)) %>% 
  select(YEAR, south_end, north_end, Borofsky, little_point) %>% 
  pivot_longer( cols = south_end:Borofsky,
               names_to = "location",
               values_to = "total") %>%
  mutate(sub_colony = case_when(location == "Borofsky" ~ "Northeast Colony",
                                location == "north_end" ~ "Northwest Colony",
                                location == "south_end" ~ "South End Colony")) %>% 
  ggplot(aes(y = total, x = YEAR, fill = sub_colony)) +
  geom_col() +
   scale_fill_viridis(discrete = T, direction = -1) +
  theme_bw()

```

```{r read-in-shapefiles}
#This code is from the nest count spatial join doc, except I couldn't figure out how to write an sf file so I'm bringing it here for the animation below... Apologies for all the extra code....
outline <- read_sf("data/outlinecolored") 
outline <- st_transform(outline, "+init=epsg:4326")

gullshape2022 <- read_sf("data/gullshapefiles/Gulls2022")
gullshape2022 <- st_transform(gullshape2022, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2022)

##2021
gullshape2021 <- read_sf("data/gullshapefiles/Gulls2021")
gullshape2021 <- st_transform(gullshape2021, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2021)

#2020
gullshape2020 <- read_sf("data/gullshapefiles/Gulls2020")
gullshape2020 <- st_transform(gullshape2020, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2020)

##2019
gullshape2019 <- read_sf("data/gullshapefiles/Gulls2019")
gullshape2019 <- st_transform(gullshape2019, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2019)
##2018
gullshape2018 <- read_sf("data/gullshapefiles/gulls2018")
gullshape2018 <- st_transform(gullshape2018, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2018)
##2017
gullshape2017 <- read_sf("data/gullshapefiles/gulls2017")
gullshape2017 <- st_transform(gullshape2017, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2017)
##2016
gullshape2016 <- read_sf("data/gullshapefiles/gulls2016")
gullshape2016 <- st_transform(gullshape2016, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2016)
##2015
gullshape2015 <- read_sf("data/gullshapefiles/gulls2015")
gullshape2015 <- st_transform(gullshape2015, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2015)
##2014
gullshape2014 <- read_sf("data/gullshapefiles/gulls2014")
gullshape2014 <- st_transform(gullshape2014, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2014)
##2013
gullshape2013 <- read_sf("data/gullshapefiles/gulls2013")
gullshape2013 <- st_transform(gullshape2013, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2013)
##2012
gullshape2012 <- read_sf("data/gullshapefiles/gulls2012")
gullshape2012 <- st_transform(gullshape2012, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2012)
##2011
gullshape2011 <- read_sf("data/gullshapefiles/gulls2011")
gullshape2011 <- st_transform(gullshape2011, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2011)
##2010
gullshape2010 <- read_sf("data/gullshapefiles/gulls2010")
gullshape2010 <- st_transform(gullshape2010, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2010)
##2009
gullshape2009 <- read_sf("data/gullshapefiles/gulls2009")
gullshape2009 <- st_transform(gullshape2009, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2009)
##2008
gullshape2008 <- read_sf("data/gullshapefiles/gulls2008")
gullshape2008 <- st_transform(gullshape2008, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2008)
##2007
gullshape2007 <- read_sf("data/gullshapefiles/gulls2007")
gullshape2007 <- st_transform(gullshape2007, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2007)
##2006
gullshape2006 <- read_sf("data/gullshapefiles/gulls2006")
gullshape2006 <- st_transform(gullshape2006, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2006)
##2005
gullshape2005 <- read_sf("data/gullshapefiles/gulls2005")
gullshape2005 <- st_transform(gullshape2005, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2005)
##2004
gullshape2004 <- read_sf("data/gullshapefiles/gulls2004")
gullshape2004 <- st_transform(gullshape2004, "+init=epsg:4326") %>%
  select(ID, geometry) %>%
  rename(flag = "ID") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2004)
##2003
gullshape2003 <- read_sf("data/gullshapefiles/gulls2003")
gullshape2003 <- st_transform(gullshape2003, "+init=epsg:4326") %>%
  select(Comment, geometry) %>%
  rename(flag = "Comment") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2003)
##2002
gullshape2002 <- read_sf("data/gullshapefiles/gulls2002")
gullshape2002 <- st_transform(gullshape2002, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2002)
##2001
gullshape2001 <- read_sf("data/gullshapefiles/gulls2001")
gullshape2001 <- st_transform(gullshape2001, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2001)
##2000
gullshape2000 <- read_sf("data/gullshapefiles/gulls2000")
gullshape2000 <- st_transform(gullshape2000, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 2000)
##1999
gullshape1999 <- read_sf("data/gullshapefiles/gulls_1999")
gullshape1999 <- st_transform(gullshape1999, "+init=epsg:4326") %>%
  select(COMMENT, geometry) %>%
  rename(flag = "COMMENT") %>%
  mutate(flag = as.integer(flag)) %>%
  mutate(year = 1999)




gullshapecombined <- rbind(gullshape2022, gullshape2021, gullshape2020, gullshape2019, gullshape2018, gullshape2017, gullshape2016, gullshape2015, gullshape2014, gullshape2013, gullshape2012, gullshape2011, gullshape2010, gullshape2009, gullshape2008, gullshape2007, gullshape2006, gullshape2005, gullshape2004, gullshape2003, gullshape2002, gullshape2001, gullshape2000, gullshape1999)
```

##Colony Animation 

```{r echo=FALSE, fig.height=5, fig.width=5, creating-animation}
animation.points.only <- ggplot(gullshapecombined) +
  geom_sf(data = outline, aes(fill = ID)) +
  geom_sf(data = gullshapecombined, color = "#00264D", aes(group = year), size = 2) +
  coord_sf(ylim = c(44.140385, 44.145726), xlim = c(-68.25038, -68.242629), expand = FALSE) + 
  scale_fill_manual(values = c("#DBE9F5", "#DBE9F5", "#BDD5E7")) +
  transition_states(year,
                    transition_length = .1,
                    state_length = 20
                    ) +
  # enter_fade() +
  # exit_fade() +
  labs(
    title = "Distribution of Nesting Gulls", 
    subtitle = 'Year: {closest_state}') +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        title = element_text(size = 20),
        plot.subtitle = element_text(size = 18))

```

```{r rendering-and-saving-animation, fig.alt="This animated map shows the changing distribution and location of herring gull nests at the south end sub colony on Great Duck Island. The y axis shows longtitude and the x axis shows lattitude. Herring gull nests are represented by dark blue points, and the outline of Great Duck is shown in light blue. This animation shows that gulls have not colonized the island in an even distribution, but rather in a series of clusters"}

animate.save <- animate(animation.points.only, duration = 40, height = 1000, width = 1000)

anim_save(animate.save, filename = "colony_animation.filled.gif")
```

##Density Graphs

```{r importing-data}
nest_density <- read_csv("data/density_habitat.csv") %>%
  select(point_id:habitat)
```

```{r fig.alt="Bar graph showing the number of herring gull nests in different habitats from 1999 to 2022. The x axis is representing the number of nests, while the y axis shows the year. The different habitats are represented by different colors. We can see that the proportion of gulls nesting on the rocky shoreline and in the vegetated meadow has stayed roughly the same over the last 24 years."}
nest_density %>%
  filter(habitat %in% c("vegetation", "berm")) %>%
  ggplot() +
  geom_bar(aes(x = year, fill = habitat), position = "dodge") +
  scale_fill_manual(values = c( "#9EC2FF", "#4259C3")) +
  theme_bw() +
  labs(title = "Number of Nesting Gulls at the South End",
       subtitle = "Colored by Habitat",
       y = "Number of Nests",
       x = "Year",
       fill = "Habitat")

ggsave("proportion_nests_by_habitat.jpeg", device = "jpeg", dpi = 500)
```


```{r fig.height=2.5, fig.width=4, fig.alt= "Bar graph showing changes in nesting density from 1999 to 2022 at the south end colony on Great Duck Island. Mean distance to nearest neighbor, measured in meters, is shown on the y axis while year is shown on the x axis. There seems to be a trend of mean distance decreasing through time, and the error is also decreasing through time"}
se <- function(x) sd(x)/sqrt(length(x))

nest_density %>%
  filter(distance_rank == 1) %>%
  group_by(year) %>%
  summarise(mean = mean(distance), se = se(distance)) %>%
  ggplot() +
  geom_col(aes(x = year, y = mean, group = year), fill = "#9EC2FF") +
  geom_errorbar(aes(x = year, ymin = (mean - se), ymax = (mean + se)), size = 0.5, width = 0.5) +
  labs(title = "Changes in Density of Nesting HERGs",
       y = "Mean Distance to Nearest Neighbor (meters)",
       x = "Year") +
  theme_bw()

ggsave("changes_in_density.jpeg", device = "jpeg", dpi = 500)
```


```{r fig.height=2, fig.width=4, fig.alt= "Same as previous graph, except that now habitat is differentiated by color. Bar graph showing changes in nesting density from 1999 to 2022 at the south end colony on Great Duck Island. Mean distance to nearest neighbor, represented in meters, is shown on the y axis while year is shown on the x axis. Error bars represent standard error. There seems to be a trend of mean distance decreasing through time, and the error is also decreasing through time"}
nest_density %>%
  filter(distance_rank == 1) %>%
  filter(habitat %in% c("berm", "vegetation")) %>%
  group_by(year, habitat) %>%
  summarise(mean = mean(distance), se = se(distance)) %>%
  ggplot() +
  geom_col(aes(x = year, y = mean, fill = habitat), position = position_dodge(preserve = "single"), width = 0.75) +
  scale_fill_manual(values = c("#4259C3", "#9EC2FF")) +
  # scale_fill_manual(values = c("#459BB7", "#8ACCDC")) +
  geom_errorbar(aes(x = year, ymin = (mean - se), ymax = (mean + se), group = habitat), size = 0.5, width = 0.5, position = position_dodge(preserve = "single", width = 0.75)) +
  labs(title = "Changes in Density of Nesting HERGs",
       subtitle = "By Habitat and Year",
       y = "Mean Distance to Nearest Neighbor (meters)",
       x = "Year",
       fill = "Habitat") +
  theme_bw()

ggsave("changes_in_density_with_habitat.jpeg", device = "jpeg", dpi = 500)

```




##Tower Count Data Visualizations

For additional exploration of tower count data, see Shiny App: https://udppk1-eleanor-gnam.shinyapps.io/towerDRAFT/\

```{r echo = FALSE, main-four-species, fig.alt = "Four line charts showing trends in four breeding species on Great Duck Island between 2000 and 2022. Year is graphed on the x axis, and the median daily count of each species is graphed on the y axis. The median daily count for each year is represented by a point with error bars that show the standard error, and the points are connected by lines." }
tower <- read_csv("data/towerclean.csv")

se <- function(x) sd(x)/sqrt(length(x))

tower %>%
  filter(species == c("herg","gbbg","blgu","coei_ad")) %>% 
  mutate(label = case_when(species == "herg" ~ "Herring Gull",
                          species == "gbbg" ~ "Great Black-backed Gull",
                          species == "blgu" ~ "Black Guillemot",
                          species == "coei_ad" ~ "Common Eider",
                          TRUE ~ as.character(species))) %>%
  group_by(species, label, year) %>% 
  mutate(med = median(count), se = se(count)) %>% 
  ggplot()+
  geom_point(aes(x = year, y = med, color = label), size = 1.8)+
  geom_errorbar(aes(x = year, ymin = (med - se), ymax = (med + se)), alpha = 1, size = 0.5, width = 0.003)+
  geom_line(aes(x = year, y = med, color = label), linewidth = 1.3)+
  scale_color_viridis_d(direction = -1) +
  theme_bw()+
  facet_wrap(~label, scales = "free", ncol = 2)+
  labs(title = "Median Counts of Species Breeding on Great Duck Island by Year", subtitle = "Error Bars Represent Standard Error", color = "")+
  ylab("Median Daily Count")+
  xlab("Year")+
  theme(legend.position = "bottom")



```


```{r echo = FALSE, atpu-razo-noga, fig.alt = "three barplots showing the mean daily count by year for four species: Atlantic Puffins, Northern Gannets, and Razorbills. Year is graphed to the x-axis, with mean daily count on the y axis. Each bar has an error bar denoting standard error for the counts within each year."  }
tower %>% 
  filter(species == "puffin") %>% 
  mutate(label = "Atlantic Puffin") %>% 
  group_by(year, label) %>% 
  summarize(mean = mean(count), se = se(count)) %>% 
  ggplot(aes(x = year, y = mean, fill = label)) +
  geom_col()+
  geom_errorbar(aes(x = year, ymin = (mean - se), ymax = (mean + se)), alpha = 1, size = 0.8, width = 0.4)+
  labs(title = "Mean Daily Count of Atlantic Puffin by Year", subtitle = "Error bars represent standard error", fill = "")+
  scale_fill_viridis_d(option = "plasma")+
  xlab("Year") +
  ylab("Mean Daily Count")+
  theme_bw()

tower %>% 
  filter(species == "noga") %>% 
  mutate(label = "Northern Gannet") %>% 
  group_by(year, label) %>% 
  summarize(mean = mean(count), se = se(count)) %>% 
  ggplot(aes(x = year, y = mean, fill = label)) +
  geom_col()+
  geom_errorbar(aes(x = year, ymin = (mean - se), ymax = (mean + se)), alpha = 1, size = 0.8, width = 0.4)+
  labs(title = "Mean Daily Count of Northern Gannet by Year", subtitle = "Error bars represent standard error", fill = "")+
  scale_fill_manual(values = "#1CCFD6")+
  xlab("Year") +
  ylab("Mean Daily Count")+
  theme_bw()

tower %>% 
  filter(species == "razo") %>% 
  mutate(label = "Razorbill") %>% 
  group_by(year, label) %>% 
  summarize(mean = mean(count), se = se(count)) %>% 
  ggplot(aes(x = year, y = mean, fill = label)) +
  geom_col()+
  geom_errorbar(aes(x = year, ymin = (mean - se), ymax = (mean + se)), alpha = 1, size = 0.8, width = 0.4)+
  labs(title = "Mean Daily Count of Razorbill by Year", subtitle = "Error bars represent standard error", fill = "")+
  scale_fill_manual(values = "#AF2892")+
  xlab("Year") +
  ylab("Mean Daily Count")+
  theme_bw()


```

```{r echo = FALSE, gull-counts-vs-nest-numbers, fig.alt = "a line chart showing the change in median herring gull tower counts per year overlaid over a barplot showing the total number of herring gull nests in the south end colony per year. Median daily herring gull count is graphed on the left y axis, and the total number of nests in the south end colony is graphed on the right y axis. Year is graphed to the x axis. The vertexes on the line representing the median daily herring gull count for each year are given error bars that denote standard error.}

#still working on this one

pop_dist_clean <- population_distribution_gulls %>%
  rename(little_point = `Little Point (near Boathouse)`) %>%
  mutate(West = as.numeric(`West`)) %>%
  mutate(south_end = East + West + Extension) %>%
  mutate(north_end = Point + Cabin + Hell) %>%
  mutate(year = YEAR) %>% 
  filter(!is.na(south_end)) %>% 
  select(year, south_end, north_end, Borofsky, little_point) %>%
  pivot_longer( cols = south_end:little_point,
               names_to = "location",
               values_to = "total")


southend1 <- pop_dist_clean %>% 
  filter(location == "south_end") %>% 
  mutate(year = as.numeric(year))


gullmeds <- tower %>%
  mutate(year = as.numeric(year)) %>% 
  filter(species == "herg") %>% 
  group_by(year, species) %>% 
  summarize(median = median(count), se = se(count)) 


ggplot() +
  geom_col(data = southend1, aes(x = year, y = total), fill = "firebrick", alpha = 0.8, color = "black") +
  geom_point(data = gullmeds, aes(x = year, y = median), color = "steelblue3", size = 2,) +
  geom_line(data = gullmeds, aes(x = year, y = median), linewidth = 1.3, color = "steelblue3") +
  geom_errorbar(data= gullmeds, aes(x = year, ymin = (median - se), ymax = (median + se)), width = 0.5, size = 0.7) +
  scale_y_continuous(name = "Total Nests on the South End", sec.axis = sec_axis(~., name = "Median Gulls Observed During Tower Count")) +
  theme_bw() +
  theme(axis.text.y.left = element_text(color = "firebrick"), axis.text.y.right = element_text(color = "steelblue4"), axis.title.y.left = element_text(color = "firebrick"), axis.title.y.right = element_text(color = "steelblue4")) +
  labs(title = "Changes in median herring gull tower counts and total herring gull nests per year", subtitle = "South end colony only", caption = "error bars show standard error") +
  xlab("year")

  
  
```

