---
title: "tower count data cleaning"
author: "Eleanor and Wriley"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      cache = TRUE, 
                      fig.width = 10,
                      fig.height = 5,
                      fig.align = "center", 
                      message = FALSE)
library(tidyverse)
library(readxl)
library(viridis)
library(hrbrthemes)
library(sf)
library(leaflet)
library(lubridate)
library(gganimate)
library(ggimage)
library(gifski)
```


```{r column rename function}
#lists of possible columns names for our usual birds, add as new ones arise
hergs <- c("gulls","hegu","HERG","Gull","# gulls", "HeGu","HerGull")
gbbgs <- c("bbgu","GBBG","BBGull")
blgus <- c("# squees", "squees","BLGU","Guillem", "BGUY", "squee","SQUEE")
coei_jus <-c("chix","eider chicks", "COEI ducklings", "Eider Chicks","COEI chix","COEI  chix","EICHICK", "coei chix")
coei_ads <- c("COEI","Eiders", "# eiders", "eider","eiders", "coei")
others <- c("Other","notes","comments","others", "Others", "comment","Comments")
dates <- c("Date")
puffins <- c("ATPU","puffs","puffins","atpu")
corms <- c("DCCO","cormorants")


#This function overwrites a variety of potential column names and replaces them with a standard name. It is not order dependent and can be used on dataframes with any number of columns and any variety of column names. It will leave columns that are not specified untouched. It can be appended as needed. 

#One possible issue may arise if a dataframe has two columns that need to be combined into one. For example, a dataframe that has both a AMCR and a CORA column cannot be processed by this function--one column will be overwritten. If that is the case, I recommend adding those columns together before doing anything to process that dataframe.  
cleancolumns <- function(inputdataframe) {
  for (i in 1:length(colnames(inputdataframe))){
      if (colnames(inputdataframe)[i] %in% hergs) {
        colnames(inputdataframe)[i] <- "herg"
        print("hergs")
    } else if(colnames(inputdataframe)[i] %in% gbbgs) {
        colnames(inputdataframe)[i] <- "gbbg"
        print("gbbgs")
    } else if (colnames(inputdataframe)[i] %in% blgus) {
      colnames(inputdataframe)[i] <- "blgu"
      print("blgus")
    } else if (colnames(inputdataframe)[i] %in% coei_jus) {
      colnames(inputdataframe)[i] <- "coei_ju"
      print("coei_jus")
    } else if (colnames(inputdataframe)[i] %in% coei_ads) {
      colnames(inputdataframe)[i] <- "coei_ad"
      print("coei_ads")
    } else if (colnames(inputdataframe)[i] %in% others) {
      colnames(inputdataframe)[i] <- "other"
      print("other")
    } else if (colnames(inputdataframe)[i] %in% dates) {
      colnames(inputdataframe)[i] <- "date"
      print("dates")
    } else if (colnames(inputdataframe)[i] %in% puffins) {
      colnames(inputdataframe)[i] <- "puffin"
      print("puffins")
    } else if (colnames(inputdataframe)[i] %in% corms) {
      colnames(inputdataframe)[i] <- "dcco"
      print("corms")
    } else if (colnames(inputdataframe)[i] %in% "COLO") {
      colnames(inputdataframe)[i] <- "colo"
      print("loon")
    } else if (colnames(inputdataframe)[i] %in% "tern") {
      colnames(inputdataframe)[i] <- "ternsp"
      print("terns")
    } else if (colnames(inputdataframe)[i] %in% "NOGA") {
      colnames(inputdataframe)[i] <- "noga"
      print("gannets")
    } else if (colnames(inputdataframe)[i] %in% "BAEA") {
      colnames(inputdataframe)[i] <- "baea"
      print("eagles")
    } else if (colnames(inputdataframe)[i] %in% "scoter") {
      colnames(inputdataframe)[i] <- "scoter"
      print("scoter")
    } else if (colnames(inputdataframe)[i] %in% "seal") {
      colnames(inputdataframe)[i] <- "seals"
      print("seals")
    } else if (colnames(inputdataframe)[i] %in% "RAZO") {
      colnames(inputdataframe)[i] <- "razo"
      print("razos")
    } else if (colnames(inputdataframe)[i] %in% "LAGU") {
      colnames(inputdataframe)[i] <- "lagu"
      print("lagus")
    } else if (colnames(inputdataframe)[i] %in% c("AMCR", "CORA","crow","corvid")) {
      colnames(inputdataframe)[i] <- "corvid"
      print("crows")
    } else if (colnames(inputdataframe)[i] %in% "SPSA") {
      colnames(inputdataframe)[i] <- "peepsp"
      print("peeps")
    }
      
  }
  return(inputdataframe)
}

```

```{r comment split function}
##This function uses regex to extract numbers of birds from the "comment" column. There is one if/else pair for every species that should be extracted, and each species has a string of possible expressions used to refer to it. Those strings can be extended to account for new species nicknames, and additional if/else phrases can be added to add new species into the eventual clean datafile. 

splitcomments <- function(inputdataframe) {
  #puffins
    if ("puffin" %in% colnames(inputdataframe)) {
        inputdataframe <- inputdataframe %>% 
        mutate(puffin = puffin)
  } else {
        inputdataframe <- inputdataframe %>% 
        mutate(puffin = str_extract(other, "\\d*puff|\\d*.puff|\\d*atpu|\\d*.atpu|\\d*puffis|\\d*puffins|\\d*.puffins|\\d*.ATPU|\\d*.ALPU|\\d*.puffin|\\d*..ATPU")) %>% 
        mutate(puffin = as.double(str_extract(puffin, "\\d*")))
        
  } 
  if ("dcco" %in% colnames(inputdataframe)) {
    #cormorants
        inputdataframe <- inputdataframe %>% 
        mutate(dcco = dcco)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(dcco = str_extract(other, "\\d*corm|\\d*dcc|\\d*dcco|\\d*ddco|\\d*.DCCO|\\d*.DCC0|\\d*.commorants|\\d*.corm|\\d*.cormorants|d*..corm|\\d*.dcco")) %>% 
         mutate(dcco = as.double(str_extract(dcco, "\\d*")))
         
  } 
  if ("ternsp" %in% colnames(inputdataframe)) {
    #terns
        inputdataframe <- inputdataframe %>% 
        mutate(ternsp = ternsp)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(ternsp = str_extract(other, "\\d*cote|\\d*.terns|\\d*.COTE|\\d*.ARTE|\\d*.Terns|\\d*.Tern|\\d*.arte|\\d*.common tern|\\d*.common term")) %>% 
         mutate(ternsp = as.double(str_extract(ternsp, "\\d*")))
         
  } 
  if ("razo" %in% colnames(inputdataframe)) {
    #razorbills
        inputdataframe <- inputdataframe %>% 
        mutate(razo = razo)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(razo = str_extract(other, "\\d*razo|\\d*razor|\\d*.RAZO|\\d*.razorbills|\\d*.bills|\\d*.bill|\\d*.RAZ0|\\d*.RABI|\\d*.razo|\\d*razo")) %>% 
         mutate(razo = as.double(str_extract(razo, "\\d*")))
         
  } 
  if ("lagu" %in% colnames(inputdataframe)) {
    #laughing gulls
        inputdataframe <- inputdataframe %>% 
        mutate(lagu = lagu)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(lagu = str_extract(other, "\\d*lagu|\\d*.laughing|\\d*.LAGU|\\d*lagus|\\d*.laughing gull|\\d*.lagu|\\d*LAGU|\\d*.laughing gulls")) %>% 
         mutate(lagu = as.double(str_extract(lagu, "\\d*")))
         
  } 
  if ("comu" %in% colnames(inputdataframe)) {
    #murres
        inputdataframe <- inputdataframe %>% 
        mutate(comu = comu)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(comu = str_extract(other, "\\d*murre|\\d*.COMU|\\d*.common murre|\\d*.murre|\\d*.comu|\\d*.common murres|\\d*COMU")) %>% 
         mutate(comu = as.double(str_extract(comu, "\\d*")))
         
  } 
  if ("baea" %in% colnames(inputdataframe)) {
    #bald eagle
        inputdataframe <- inputdataframe %>% 
        mutate(baea = baea)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(baea = str_extract(other, "\\d*.imm|\\d*.BAEA|\\d*.eagle|\\d*.juv")) %>% 
         mutate(baea = as.double(str_extract(baea, "\\d*")))
         
  } 
  if ("noga" %in% colnames(inputdataframe)) {
    #gannet
        inputdataframe <- inputdataframe %>% 
        mutate(noga = noga)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(noga = str_extract(other, "\\d*.gannets|\\d*.NOGA|\\d*.gannet")) %>% 
         mutate(noga = as.double(str_extract(noga, "\\d*")))
         
  } 
  if ("corvid" %in% colnames(inputdataframe)) {
    #corvid
        inputdataframe <- inputdataframe %>% 
        mutate(corvid = corvid)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(corvid = str_extract(other, "\\d*.crow|\\d*.Corvid|\\d*.AMCR|\\d*.Corvids|\\d*.crows|\\d*crow|\\d*.CORA")) %>% 
         mutate(corvid = as.double(str_extract(corvid, "\\d*")))
         
  } 
  if ("peepsp" %in% colnames(inputdataframe)) {
    #sandpipers
        inputdataframe <- inputdataframe %>% 
        mutate(peepsp = peepsp)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(peepsp = str_extract(other, "\\d*.SPSA|\\d*.WHIM|\\d*..SPSA|\\d*.spotted sandpiper|\\d*.least sandpiper|\\d*.pipers|\\d*.common sandpipers|\\d*.piper|\\d*.red knots|\\d*.wimbrel|\\d*.spotted sandpipers|\\d*.sandpiper|\\d*.sandpipers|\\d*.RUTU|\\d*.SESA|d*.SBDO|\\d*.REPH|\\d*.LESA")) %>% 
         mutate(peepsp = as.double(str_extract(peepsp, "\\d*")))
         
  } 
  if ("seals" %in% colnames(inputdataframe)) {
    #seals
        inputdataframe <- inputdataframe %>% 
        mutate(seals = seals)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(seals = str_extract(other, "\\d*.Seal|\\d*.Seals|\\d*.Harbor|\\d*.Gray|\\d*.seals|\\d*.grey|\\d*.seal|\\d*.harbor|\\d*.gray|\\*.Grey|\\d*.Grey Seal|\\d*.Grey Seals|\\d*.harbor seal|\\d*.gray seal")) %>% 
         mutate(seals = as.double(str_extract(seals, "\\d*")))
         
  } 
  if ("colo" %in% colnames(inputdataframe)) {
    #loon
        inputdataframe <- inputdataframe %>% 
        mutate(colo = colo)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(colo = str_extract(other, "\\d*.COLO|\\d*.loon|\\d*.loons")) %>% 
         mutate(colo = as.double(str_extract(colo, "\\d*")))
         
  } 
  if ("cago" %in% colnames(inputdataframe)) {
    #geese
        inputdataframe <- inputdataframe %>% 
        mutate(cago = cago)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(cago = str_extract(other, "\\d*.CAGO|\\d*.goose|\\d*.canada goose|\\d*.canada geese")) %>% 
         mutate(cago = as.double(str_extract(cago, "\\d*")))
         
  } 
  if ("porpoise" %in% colnames(inputdataframe)) {
    #porpoise
        inputdataframe <- inputdataframe %>% 
        mutate(porpoise = porpoise)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(porpoise = str_extract(other, "\\d*.Harbor porpoise|\\d*.porpoise|\\d*.Porpoises|\\d*.porpoises")) %>% 
         mutate(porpoise = as.double(str_extract(porpoise, "\\d*")))
         
  } 
  if ("raptor" %in% colnames(inputdataframe)) {
    #raptor
        inputdataframe <- inputdataframe %>% 
        mutate(raptor = raptor)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(raptor = str_extract(other, "\\d*.tv|\\d*.peregrine|\\d*.PEFA|\\d*.MERL")) %>% 
         mutate(raptor = as.double(str_extract(raptor, "\\d*")))
         
  } 
  if ("shearwater" %in% colnames(inputdataframe)) {
    #shearwater
        inputdataframe <- inputdataframe %>% 
        mutate(shearwater = shearwater)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(shearwater = str_extract(other, "\\d*.shearwater|\\d*.GRSH|\\d*.GRSHE")) %>% 
         mutate(shearwater = as.double(str_extract(shearwater, "\\d*")))
         
  } 
  if ("gbhe" %in% colnames(inputdataframe)) {
    #herons
        inputdataframe <- inputdataframe %>% 
        mutate(gbhe = gbhe)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(gbhe = str_extract(other, "\\d*.heron|\\d*.GBHE|\\d*.great blue heron")) %>% 
         mutate(gbhe = as.double(str_extract(gbhe, "\\d*")))
         
  } 
  if ("scoter" %in% colnames(inputdataframe)) {
    #scoter
        inputdataframe <- inputdataframe %>% 
        mutate(scoter = scoter)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(scoter = str_extract(other, "\\d*.scoter|\\d*.Scoter|\\d*.BLSC|\\d*.surf scoter|\\d*.SUSC")) %>% 
         mutate(scoter = as.double(str_extract(scoter, "\\d*")))
         
  } 
  if ("wisp" %in% colnames(inputdataframe)) {
    #Wilson's Storm-Petrel
        inputdataframe <- inputdataframe %>% 
        mutate(wisp = wisp)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(wisp = str_extract(other, "\\d*.WISP")) %>% 
         mutate(wisp = as.double(str_extract(wisp, "\\d*")))
         
  } 
  if ("lbbg" %in% colnames(inputdataframe)) {
    #LBBG
        inputdataframe <- inputdataframe %>% 
        mutate(lbbg = lbbg)
  } else {
         inputdataframe <- inputdataframe %>% 
         mutate(lbbg = str_extract(other, "\\d*.LBBG")) %>% 
         mutate(lbbg = as.double(str_extract(lbbg, "\\d*")))
  }
 return(inputdataframe)
}
     
```      
    

```{r select columns and pivot}

#This function selects the columns organized by the functions above, then pivots them to create a long dataframe where species is a single column. If new species are added to the splitcomments function, they must also be added to the list of columns athat are selected and pivoted in order to appear in the final dataframe. 

selectcolumns <- function(inputdataframe) {
  r <- inputdataframe %>% 
    mutate(notes = other) %>% 
    select("date","herg","gbbg","coei_ad","coei_ju","blgu","other","puffin","dcco","ternsp","razo","lagu","comu","baea","noga","corvid","peepsp","seals","colo","cago","porpoise","raptor","gbhe","scoter","shearwater","notes","wisp","lbbg") %>% 
    mutate(herg = as.numeric(herg), gbbg = as.numeric(gbbg), coei_ad = as.double(coei_ad), coei_ju = as.double(coei_ju), blgu = as.double(blgu)) %>% 
    pivot_longer(cols = c("herg","gbbg","coei_ad","coei_ju","blgu","puffin","dcco","ternsp","razo","lagu","comu","baea","noga","corvid","peepsp","seals","colo","cago","porpoise","raptor", "gbhe","scoter","shearwater","wisp","lbbg"),
                 names_to = "species",
                 values_to = "count") %>% 
    select(date, species, count, notes)
  return(r)
}
```


```{r 2000}
tower_count_2000 <- read_excel("data/tower_count/tower_count_2000.XLS")
tower_count_2000 <- tower_count_2000[2:32,]
tower_count_2000 <- tower_count_2000 %>%
  mutate(coei_ju = as.double(str_extract(`# eiders`, "(?<=\\().*(?=\\))"))) %>% 
  mutate(`# eiders` = as.double(str_extract(`# eiders`, "\\d*"))) %>% 
  mutate(gbbg = NA)


tower_count_2000 <- cleancolumns(tower_count_2000)
tower_count_2000 <- splitcomments(tower_count_2000)
tower_2000_clean <- selectcolumns(tower_count_2000)
tower_2000_clean$year = 2000
```




```{r 2001}
tower_count_2001 <- read_excel("data/tower_count/tower_count_2001.xlsx", skip = 2)
tower_count_2001 <- tower_count_2001 %>% 
  mutate(GBBG = case_when(GBBG == "-" ~ "NA",
         TRUE ~ as.character(GBBG)))

tower_count_2001 <- cleancolumns(tower_count_2001)
tower_count_2001 <- splitcomments(tower_count_2001)
tower_2001_clean <- selectcolumns(tower_count_2001)
tower_2001_clean$year = 2001
```

```{r 2002}
tower_count_2002 <- read_excel("data/tower_count/tower_count_2002.xlsx", skip = 2)

tower_2002_clean <- tower_count_2002 %>% 
  cleancolumns() %>% 
  splitcomments() %>% 
  selectcolumns()

tower_2002_clean$year = 2002
```

```{r 2003}
tower_count_2003 <- read_excel("data/tower_count/tower_count_2003.xls")

#where eider chicks and adults are recorded in the same column with dashes or parens or slashes to separate them, it is necessary to manually extract those numbers. 
tower_count_2003 <- tower_count_2003 %>% 
  mutate(coei_ad = str_extract(Eider, "^(.+)/|^(.+)")) %>% 
  mutate(coei_ad = as.double(str_extract(coei_ad,"\\d*"))) %>%
  mutate(coei_ju = str_extract(Eider, "\\/.*")) %>% 
  mutate(coei_ju = as.double(str_extract(coei_ju, "\\d*$")))

tower_count_2003 <- cleancolumns(tower_count_2003)
tower_count_2003 <- splitcomments(tower_count_2003)
tower_2003_clean <- selectcolumns(tower_count_2003)
tower_2003_clean$year = 2003
```

```{r 2005}
tower_count_2005 <- read_excel("data/tower_count/tower_count_2005.xls")

tower_count_2005 <- tower_count_2005 %>% 
  mutate(other = NA)

tower_count_2005 <- cleancolumns(tower_count_2005)
tower_count_2005 <- splitcomments(tower_count_2005)
tower_2005_clean <- selectcolumns(tower_count_2005)
tower_2005_clean$year = 2005
```

```{r 2006}
tower_count_2006 <- read_excel("data/tower_count/tower_count_2006.xls")

tower_count_2006 <- cleancolumns(tower_count_2006)
tower_count_2006 <- splitcomments(tower_count_2006)
tower_count_2006 <- tower_count_2006 %>% 
  mutate(coei_ju = as.double(str_extract(other, "\\d*eiderchix")))
tower_2006_clean <- selectcolumns(tower_count_2006)
tower_2006_clean$year = 2006
```

```{r 2007}
tower_count_2007 <- read_excel("data/tower_count/tower_count_2007.xls")

tower_count_2007 <- cleancolumns(tower_count_2007)
tower_count_2007 <- splitcomments(tower_count_2007)
tower_2007_clean <- selectcolumns(tower_count_2007)
tower_2007_clean$year = 2007
```

```{r 2008}
tower_count_2008 <- read_excel("data/tower_count/tower_count_2008.xlsx", skip = 2)

tower_count_2008 <- cleancolumns(tower_count_2008)
tower_count_2008 <- splitcomments(tower_count_2008)
tower_2008_clean <- selectcolumns(tower_count_2008)
tower_2008_clean$year = 2008

```

```{r 2009}
tower_count_2009 <- read_excel("data/tower_count/tower_count_2009.xlsx", skip = 2)

tower_count_2009 <- cleancolumns(tower_count_2009)
tower_count_2009 <- splitcomments(tower_count_2009)
tower_2009_clean <- selectcolumns(tower_count_2009)
tower_2009_clean$year = 2009
```

```{r 2010}
tower_count_2010 <- read_excel("data/tower_count/tower_count_2010.xlsx",skip = 2)

tower_2010_clean <- tower_count_2010 %>% 
  cleancolumns() %>% 
  splitcomments() %>% 
  selectcolumns()

tower_2010_clean$year = 2010

```


```{r 2011}
tower_count_2011 <- read_excel("data/tower_count/tower_count_2011.xls", skip = 2)
tower_count_2011 <- tower_count_2011[1:47,]
tower_count_2011 <- tower_count_2011 %>% 
  mutate(year = "2011") %>% 
  mutate(day = str_sub(Date, start = 1, end = 2)) %>% 
  mutate(monthch = str_sub(Date, start = 3,)) %>% 
  mutate(month = case_when(monthch %in% "June" ~ "6",
                           monthch %in% " June" ~ "6",
                           monthch %in% " July" ~ "7",
                           monthch %in% " August" ~ "8",
                           monthch %in% "July" ~ "7",
                           monthch %in% "August" ~ "8",
                           TRUE ~ ""
                           )) %>% 
  select(-Comments)

tower_count_2011 <- cleancolumns(tower_count_2011)
tower_count_2011 <- splitcomments(tower_count_2011)
tower_2011_clean <- selectcolumns(tower_count_2011)
tower_2011_clean$year = 2011

```


```{r 2012}
 
tower_count_2012 <- read_excel("data/tower_count/tower_count_2012.xls", skip = 2) 

tower_count_2012 <- cleancolumns(tower_count_2012)
tower_count_2012 <- splitcomments(tower_count_2012)
tower_2012_clean <- selectcolumns(tower_count_2012)
tower_2012_clean$year = 2012
```

```{r 2013}


 tower_count_2013 <- read_excel("data/tower_count/tower_count_2013.xls") 

tower_count_2013 <- cleancolumns(tower_count_2013)
tower_count_2013 <- splitcomments(tower_count_2013)
tower_2013_clean <- selectcolumns(tower_count_2013)
tower_2013_clean$year = 2013
```

```{r 2014}
tower_count_2014 <- read_excel("data/tower_count/tower_count_2014.xlsx")
#thank god a normal one

tower_count_2014 <- cleancolumns(tower_count_2014)
tower_count_2014 <- splitcomments(tower_count_2014)
tower_2014_clean <- selectcolumns(tower_count_2014)
tower_2014_clean$year = 2014
```

```{r 2015}
tower_count_2015 <- read_excel("data/tower_count/tower_count_2015.xlsx")

tower_count_2015 <- cleancolumns(tower_count_2015)
tower_count_2015 <- splitcomments(tower_count_2015)
tower_2015_clean <- selectcolumns(tower_count_2015)
tower_2015_clean$year = 2015
```

```{r 2016}
tower_count_2016 <- read_excel("data/tower_count/tower_count_2016.xlsx")

tower_count_2016 <- cleancolumns(tower_count_2016)
tower_count_2016 <- splitcomments(tower_count_2016)
tower_2016_clean <- selectcolumns(tower_count_2016)
tower_2016_clean$year = 2016
```


```{r 2017}
tower_count_2017 <- read_excel("data/tower_count/tower_count_2017.xlsx") %>% 
  mutate(coei_ad = str_extract(`COEI + chix`, "^(.+)[\\+]|\\d*")) %>% 
  mutate(coei_ad = as.double(str_extract(coei_ad,"\\d*"))) %>%
  mutate(coei_ju = str_extract(`COEI + chix`, "[\\+].*")) %>% 
  mutate(coei_ju = as.double(str_extract(coei_ju, "\\d*$"))) %>% 
  select(-`COEI + chix`)

tower_count_2017 <- cleancolumns(tower_count_2017)
tower_count_2017 <- splitcomments(tower_count_2017)
tower_2017_clean <- selectcolumns(tower_count_2017)
tower_2017_clean$year = 2017
```

```{r 2018}
tower_count_2018 <- read_excel("data/tower_count/tower_count_2018.xlsx")

tower_count_2018 <- cleancolumns(tower_count_2018)
tower_count_2018 <- splitcomments(tower_count_2018)
tower_2018_clean <- selectcolumns(tower_count_2018)
tower_2018_clean$date[tower_2018_clean$date == "2008-05-28"] <- "2018-05-28"
tower_2018_clean$year = 2018
```

```{r 2019}
tower_count_2019 <- read_excel("data/tower_count/tower_count_2019.xlsx")

tower_count_2019 <- cleancolumns(tower_count_2019)
tower_count_2019 <- splitcomments(tower_count_2019)
tower_2019_clean <- selectcolumns(tower_count_2019)
tower_2019_clean$year = 2019
```


```{r 2020}
tower_count_2020 <- read_excel("data/tower_count/tower_count_2020.xlsx")

tower_count_2020 <- cleancolumns(tower_count_2020)
tower_count_2020 <- splitcomments(tower_count_2020)
tower_2020_clean <- selectcolumns(tower_count_2020)
tower_2020_clean$year = 2020
```

```{r 2021}

tower_count_2021 <- read_excel("data/tower_count/tower_count_2021.xlsx")

tower_count_2021 <- cleancolumns(tower_count_2021)
tower_count_2021 <- splitcomments(tower_count_2021)
tower_2021_clean <- selectcolumns(tower_count_2021)
tower_2021_clean$year = 2021

```

```{r 2022}
tower_count_2022 <- read_excel("data/tower_count/tower_count_2022.xlsx")

tower_count_2022 <- cleancolumns(tower_count_2022)
tower_count_2022 <- splitcomments(tower_count_2022)
tower_2022_clean <- selectcolumns(tower_count_2022)
tower_2022_clean$year = 2022
```

#add new code chunks as necessary for future years' data. 

```{r}
#This binds all the years together. Can be updated to add new years. 
tower <- rbind(tower_2000_clean,tower_2001_clean,tower_2002_clean,tower_2003_clean,tower_2005_clean,tower_2006_clean,tower_2007_clean,tower_2008_clean,tower_2009_clean,tower_2010_clean,tower_2011_clean,tower_2012_clean,tower_2013_clean,tower_2014_clean,tower_2015_clean, tower_2016_clean,tower_2017_clean,tower_2018_clean,tower_2019_clean, tower_2020_clean, tower_2021_clean, tower_2022_clean)

towertowrite <- tower %>% 
  mutate(count = ifelse(is.na(count), 0, count))
           
#write.csv(towertowrite, "data/towerclean.csv")
```



