---
title: "Nest Count Data Cleaning"
author: "Eleanor and Wriley"
date: "16 March 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(sf)
library(leaflet)
library(glue)
```

```{r clean-2022}
nest_count_2022 <- read_excel("data/nest_count/nest_count_2022.xlsx", na = "NA")

nest_count_2022 <- nest_count_2022 %>%
  mutate(year = "2022") %>%
  mutate(species = str_extract(comment, "\\d*GBBG|\\d*COEI")) %>%
  mutate(species = str_replace(species, "COEI", "coei")) %>%
  mutate(species = str_replace(species, "GBBG", "gbbg")) %>%
  replace_na(list(species = "herg")) %>%
  select(Flag, clutch, location, year, species) %>%
  rename(flag = Flag)
```

```{r clean-2021}
nest_count_2021 <- read_excel("data/nest_count/nest_count_2021.xlsx", na = "NA")

nest_count_2021 <- nest_count_2021 %>%
  mutate(year = "2021") %>%
    mutate(detect.gbbg = str_detect(comment, "GBBG")) %>% 
    mutate(detect.gbbg.2 = str_detect(`...7`, "GBBG")) %>%
    mutate(detect.coei = str_detect(comment, "eider")) %>%
    mutate(detect.coei.2 = str_detect(`...7`, "COEI")) %>%
    mutate(species = case_when(
      detect.gbbg == "TRUE" | detect.gbbg.2 == "TRUE" ~ "gbbg",
      detect.coei == "TRUE" | detect.coei.2 == "TRUE" ~ "coei")) %>%
  replace_na(list(species = "herg")) %>%
  select(flag, clutch, location, year, species)
```

```{r clean-2020}
nest_count_2020 <- read_excel("data/nest_count/nest_count_2020.xlsx", na = "NA")

unique(nest_count_2020$comment)
head(nest_count_2020)

nest_count_2020 <- nest_count_2020 %>%
  mutate(year = "2020") %>%
  mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))) %>%
  select(flag, clutch, location, year, species)
```

```{r clean-2019}
nest_count_2019 <- read_excel("data/nest_count/nest_count_2019.xlsx", na = "NA")

unique(nest_count_2019$comment)

nest_count_2019 <- nest_count_2019 %>%
  mutate(year = "2019") %>%
  mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))) %>%
  select(nest, clutch, location, year, species) %>%
  rename(flag = nest)
```
```{r clean-2018}
nest_count_2018 <- read_excel("data/nest_count/nest_count_2018.xlsx", na = "NA")

unique(nest_count_2018$comment)

nest_count_2018 <- nest_count_2018 %>%
  mutate(year = "2018") %>%
  mutate(species = ifelse(grepl("Black-back", comments), "gbbg",
                          ifelse(grepl("Black back", comments), "gbbg",
                          ifelse(grepl("black-back", comments), "gbbg",
                          ifelse(grepl("Black-Back", comments), "gbbg",
                          ifelse(grepl("GBBG", comments), "gbbg",
                          ifelse(grepl("gbbg", comments), "gbbg",
                          ifelse(grepl("Eider", comments), "coei",
                          ifelse(grepl("eider", comments), "coei", 
                          ifelse(grepl("Edier", comments), "coei",
                          ifelse(grepl("COEI", comments), "coei",
                          ifelse(grepl("coei", comments), "coei",
                          "herg")))))))))))) %>%
  select(nest, clutch, location, year, species) %>%
  rename(flag = nest)

```
```{r clean-2017}
nest_count_2017 <- read_excel("data/nest_count/nest_count_2017.xlsx", na = "NA")

unique(nest_count_2017$comment)

nest_count_2017 <- nest_count_2017 %>%
  mutate(year = "2017") %>%
  rename(comment = "Desc.",
         location = "loc.",
         clutch = Clutch,
         flag = Nest) %>%
  mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))) %>%
  select(flag, clutch, location, year, species)
```
```{r clean-2016}
nest_count_2016 <- read_excel("data/nest_count/nest_count_2016.xlsx", na = "NA")

nest_count_2016 <- nest_count_2016 %>%
  mutate(year = "2016") %>%
   rename(comment = "Info",
         clutch = Clutch,
         flag = Flag) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))) %>%
  select(flag, clutch, year, species) 
```

```{r clean-2015}
nest_count_2015 <- read_excel("data/nest_count/nest_count_2015.xlsx", na = "NA")

nest_count_2015 <- nest_count_2015 %>%
  mutate(year = "2015") %>%
   rename(comment = "Info",
         clutch = Clutch,
         flag = Flag) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))) %>%
  select(flag, clutch, year, species) 


```

```{r clean-2014}
nest_count_2014 <- read_excel("data/nest_count/nest_count_2014.xlsx", na = "NA")

nest_count_2014 <- nest_count_2014 %>%
  mutate(year = "2014") %>%
   rename(comment = "Species",
         clutch = "Clutch size",
         flag = "Flag #",
         location = Location) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("b", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))) %>%
  select(flag, clutch, year, species) 
```
```{r clean-2013}
nest_count_2013 <- read_excel("data/nest_count/nest_count_2013.xlsx", na = "NA")

nest_count_2013 <- nest_count_2013 %>%
  mutate(year = "2013") %>%
   # rename(comment = "Species",
   #       clutch = "Clutch size",
   #       flag = "Flag #",
   #       location = Location) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("b", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))) %>%
  select(flag, clutch, year, species)
```

```{r clean-2012}
nest_count_2012 <- read_excel("data/nest_count/nest_count_2012.xlsx", na = "NA")

nest_count_2012 <- nest_count_2012 %>%
  mutate(year = "2012") %>%
   # rename(comment = "Species",
   #       clutch = "Clutch size",
   #       flag = "Flag #",
   #       location = Location) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("b", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))))) %>%
  select(flag, clutch, year, location, species)
```

```{r clean-2011}
nest_count_2011 <- read_excel("data/nest_count/nest_count_2011.xls", na = "NA")

nest_count_2011 <- nest_count_2011 %>%
  mutate(year = "2011") %>%
   # rename(comment = "Species",
   #       clutch = "Clutch size",
   #       flag = "Flag #",
   #       location = Location) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("b", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))))))) %>%
  select(flag, clutch, year, location, species)
```

```{r clean-2010}
##NEED TO DEAL WITH LATER SUPER UNTIDY
nest_count_2010.a <- read_excel("data/nest_count/nest_count_2010.xls", na = "NA", range = ("A2:C106"))
nest_count_2010.a <- nest_count_2010.a %>%
  mutate(location = "west_side") %>%
  rename(flag = Flag,
         clutch = Clutch) %>%
  select(flag, clutch, location)

nest_count_2010.b <- read_excel("data/nest_count/nest_count_2010.xls", na = "NA", range = ("D2:E63"))
nest_count_2010.b <- nest_count_2010.b %>%
  mutate(location = "borofsky_extension") %>%
  rename(clutch = Clutch) %>%
  mutate(flag = "") %>%
  select(flag, clutch, location)

nest_count_2010.c <- read_excel("data/nest_count/nest_count_2010.xls", na = "NA", range = ("G1:H113"))
nest_count_2010.c <- nest_count_2010.c %>%
  mutate(location = "borofsky",
         flag = "") %>%
  rename(clutch = "Borofsky's") %>%
  select(flag, clutch, location)

nest_count_2010.d <- read_excel("data/nest_count/nest_count_2010.xls", na = "NA", range = ("J2:K40"))
nest_count_2010.d <- nest_count_2010.d %>%
  rename(flag = Flag,
         clutch = Clutch) %>%
  mutate(location = "east_side") %>%
  select(flag, clutch, location)

nest_count_2010 <- rbind(nest_count_2010.a, nest_count_2010.b, nest_count_2010.c, nest_count_2010.d) %>%
  mutate(flag.test = str_extract(flag, "\\d*")) %>%
  mutate(clutch.test = str_extract(clutch, "\\d*")) %>%
  mutate(comment = paste(flag, clutch)) %>%
  mutate(year = "2010") %>%
  rename(flag.pre = flag,
         clutch.pre = clutch,
         flag = flag.test,
         clutch = clutch.test) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("(bb)", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))))))) %>%
  select(flag, clutch, year, location, species)

```

```{r clean-2009}
nest_count_2009 <- read_excel("data/nest_count/nest_count_2009.xls", na = "NA")

nest_count_2009 <- nest_count_2009 %>%
  mutate(year = "2009") %>%
   rename(clutch = "CLUTCH",
         flag = "FLAG",
         location = "LOCATION") %>%
  mutate(comment = paste(COMMENT, location, seperate = "/")) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("b", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))))))))) %>%
  select(flag, clutch, year, location, species)

```
```{r clean-2008}
nest_count_2008 <- read_excel("data/nest_count/nest_count_2008.xls", na = "NA")

nest_count_2008 <- nest_count_2008 %>%
  mutate(year = "2008") %>%
   rename(note = comment,
          desc = species) %>%
  mutate(comment = paste(note, desc)) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))))))) %>%
  select(flag, clutch, year, location, species)
```

```{r clean-2007}
nest_count_2007 <- read_excel("data/nest_count/nest_count_2007.xls", sheet = "Sheet1", na = "NA")
nest_count_2007.eider <- read_excel("data/nest_count/nest_count_2007.xls", 
    sheet = "Sheet2")

nest_count_2007 <- nest_count_2007 %>%
  select(flag, clutch, comment, location) %>%
  rbind(nest_count_2007.eider)
  
  
nest_count_2007 <- nest_count_2007 %>%
  mutate(year = "2007") %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))))))) %>%
  select(flag, clutch, year, location, species)

```
```{r clean-2006}
nest_count_2006 <- read_excel("data/nest_count/nest_count_2006.xls", na = "NA")

nest_count_2006 <- nest_count_2006 %>%
  mutate(year = "2006") %>%
   rename(note = comment,
         gull.sp = species,
         flag = "number",
         location = "colony") %>%
  mutate(comment = paste(note, gull.sp, seperate = "/")) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("b", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))))))))) %>%
  select(flag, clutch, year, location, species)
```

```{r clean-2005}
nest_count_2005 <- read_excel("data/nest_count/nest_count_2005.xls", na = "NA")

nest_count_2005 <- nest_count_2005 %>%
  mutate(year = "2005") %>%
  rename(location = colony,
         flag = number) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))))))) %>%
  select(flag, clutch, year, location, species)
```

```{r clean-2004}
nest_count_2004 <- read_excel("data/nest_count/nest_count_2004.xls", na = "NA")

nest_count_2004 <- nest_count_2004 %>%
  mutate(year = "2004") %>%
  rename(flag = nest,
         comment = comments) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))))))) %>%
  select(flag, clutch, year, location, species)
```

```{r clean-2003}
nest_count_2003 <- read_excel("data/nest_count/nest_count_2003.xls", na = "NA")

nest_count_2003 <- nest_count_2003 %>%
  mutate(year = "2003") %>%
  rename(flag = nest,
         species.a = species,
         location = colony) %>%
  mutate(comment = paste(species.a, comments)) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))))))) %>%
  select(flag, clutch, year, location, species)

```

```{r clean-2002}
nest_count_2002 <- read_excel("data/nest_count/nest_count_2002.xls", na = "NA")

nest_count_2002 <- nest_count_2002 %>%
  mutate(year = "2002") %>%
  rename(flag = nest,
         species.a = species,
         location = colony) %>%
  mutate(comment = paste(species.a, comments)) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))))))) %>%
  select(flag, clutch, year, location, species)
```

```{r clean-2001}
nest_count_2001 <- read_excel("data/nest_count/nest_count_2001.xls", na = "NA", range = ("A1:D793"))

nest_count_2001 <- nest_count_2001 %>%
  mutate(year = "2001") %>%
  rename(flag = "NEST$",
         clutch = "CLUTCH",
         chick = "CHICK$",
         location = "COMMENTS$") %>%
  mutate(comment = paste(location, chick)) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))))))) %>%
  select(flag, clutch, year, location, species)

nest_count_2001$flag <- as.double(nest_count_2001$flag)
```

```{r clean-2000}
nest_count_2000 <- read_excel("data/nest_count/nest_count_2000.xls", na = "NA")

nest_count_2000 <- nest_count_2000 %>%
  mutate(year = "2000") %>%
  rename(flag = nest,
         comment = note) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("bb", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg")))))))))))))))))) %>%
  rename(location = comment) %>%
  select(flag, clutch, year, location, species)
```

```{r clean-1999}
nest_count_1999 <- read_excel("data/nest_count/nest_count_1999.xls", na = "NA")

nest_count_1999 <- nest_count_1999 %>%
  mutate(year = "1999") %>%
  rename(flag = nest,
         location = area) %>%
 mutate(species = ifelse(grepl("Black-back", comment), "gbbg",
                          ifelse(grepl("Black back", comment), "gbbg",
                          ifelse(grepl("black-back", comment), "gbbg",
                          ifelse(grepl("Black-Back", comment), "gbbg",
                          ifelse(grepl("Blackback", comment), "gbbg",
                          ifelse(grepl("blackback", comment), "gbbg",
                          ifelse(grepl("Black", comment), "gbbg",
                          ifelse(grepl("black", comment), "gbbg",
                          ifelse(grepl("GBBG", comment), "gbbg",
                          ifelse(grepl("BBG", comment), "gbbg",
                          ifelse(grepl("bb", comment), "gbbg",
                          ifelse(grepl("gbbg", comment), "gbbg",
                          ifelse(grepl("Eider", comment), "coei",
                          ifelse(grepl("EIDER", comment), "coei",
                          ifelse(grepl("eider", comment), "coei", 
                          ifelse(grepl("Edier", comment), "coei",
                          ifelse(grepl("COEI", comment), "coei",
                          ifelse(grepl("coei", comment), "coei",
                          "herg"))))))))))))))))))) %>%
  select(flag, clutch, year, location, species)
```

```{r}
#Uncomment to write fresh csv files
# write.csv(nest_count_2022, "data/nest_count_clean_2022.csv")
# write.csv(nest_count_2021, "data/nest_count_clean_2021.csv")
# write.csv(nest_count_2020, "data/nest_count_clean_2020.csv")
# write.csv(nest_count_2019, "data/nest_count_clean_2019.csv")
# write.csv(nest_count_2018, "data/nest_count_clean_2018.csv")
# write.csv(nest_count_2017, "data/nest_count_clean_2017.csv")
# write.csv(nest_count_2016, "data/nest_count_clean_2016.csv")
# write.csv(nest_count_2015, "data/nest_count_clean_2015.csv")
# write.csv(nest_count_2014, "data/nest_count_clean_2014.csv")
# write.csv(nest_count_2013, "data/nest_count_clean_2013.csv")
# write.csv(nest_count_2012, "data/nest_count_clean_2012.csv")
# write.csv(nest_count_2011, "data/nest_count_clean_2011.csv")
# write.csv(nest_count_2010, "data/nest_count_clean_2010.csv")
# write.csv(nest_count_2009, "data/nest_count_clean_2009.csv")
# write.csv(nest_count_2008, "data/nest_count_clean_2008.csv")
# write.csv(nest_count_2007, "data/nest_count_clean_2007.csv")
# write.csv(nest_count_2006, "data/nest_count_clean_2006.csv")
# write.csv(nest_count_2005, "data/nest_count_clean_2005.csv")
# write.csv(nest_count_2004, "data/nest_count_clean_2004.csv")
# write.csv(nest_count_2003, "data/nest_count_clean_2003.csv")
# write.csv(nest_count_2002, "data/nest_count_clean_2002.csv")
# write.csv(nest_count_2001, "data/nest_count_clean_2001.csv")
# write.csv(nest_count_2000, "data/nest_count_clean_2000.csv")
# write.csv(nest_count_1999, "data/nest_count_clean_1999.csv")
```

```{r join-nest-counts}
nest_count_clean_2022 <- read.csv("data/nest_count_clean/nest_count_clean_2022.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2021 <- read.csv("data/nest_count_clean/nest_count_clean_2021.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2020 <- read.csv("data/nest_count_clean/nest_count_clean_2020.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2019 <- read.csv("data/nest_count_clean/nest_count_clean_2019.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2018 <- read.csv("data/nest_count_clean/nest_count_clean_2018.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2017 <- read.csv("data/nest_count_clean/nest_count_clean_2017.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2016 <- read.csv("data/nest_count_clean/nest_count_clean_2016.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2015 <- read.csv("data/nest_count_clean/nest_count_clean_2015.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2014 <- read.csv("data/nest_count_clean/nest_count_clean_2014.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2013 <- read.csv("data/nest_count_clean/nest_count_clean_2013.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2012 <- read.csv("data/nest_count_clean/nest_count_clean_2012.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2011 <- read.csv("data/nest_count_clean/nest_count_clean_2011.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2010 <- read.csv("data/nest_count_clean/nest_count_clean_2010.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2009 <- read.csv("data/nest_count_clean/nest_count_clean_2009.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2008 <- read.csv("data/nest_count_clean/nest_count_clean_2008.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2007 <- read.csv("data/nest_count_clean/nest_count_clean_2007.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2006 <- read.csv("data/nest_count_clean/nest_count_clean_2006.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2005 <- read.csv("data/nest_count_clean/nest_count_clean_2005.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2004 <- read.csv("data/nest_count_clean/nest_count_clean_2004.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2003 <- read.csv("data/nest_count_clean/nest_count_clean_2003.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2002 <- read.csv("data/nest_count_clean/nest_count_clean_2002.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2001 <- read.csv("data/nest_count_clean/nest_count_clean_2001.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_2000 <- read.csv("data/nest_count_clean/nest_count_clean_2000.csv") %>%
  select(flag, year, species, clutch)
nest_count_clean_1999 <- read.csv("data/nest_count_clean/nest_count_clean_1999.csv") %>%
  select(flag, year, species, clutch)

all.nest.count <- rbind(nest_count_clean_2022, 
                        nest_count_clean_2021,
                        nest_count_clean_2020,
                        nest_count_clean_2019,
                        nest_count_clean_2018,
                        nest_count_clean_2017,
                        nest_count_clean_2016,
                        nest_count_clean_2015,
                        nest_count_clean_2014,
                        nest_count_clean_2013,
                        nest_count_clean_2012,
                        nest_count_clean_2011,
                        nest_count_clean_2010,
                        nest_count_clean_2009,
                        nest_count_clean_2008,
                        nest_count_clean_2007,
                        nest_count_clean_2006,
                        nest_count_clean_2005,
                        nest_count_clean_2004,
                        nest_count_clean_2003,
                        nest_count_clean_2002,
                        nest_count_clean_2001,
                        nest_count_clean_2000,
                        nest_count_clean_1999)

#Uncomment to write a fresh file
#write.csv(all.nest.count, "data/all.nest.count.csv")
```

